before:
  hooks:
    - go generate ./...
project_name: sipproxy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w"
  binary: sipproxy
  flags:
  - -tags=release
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - "386"
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  - "7"
  hooks:
    post: ./upx.sh
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  wrap_in_directory: true
  files:
  - none*
  replacements:
    amd64: 64-bit
    386: 32-bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
release:
  github:
    owner: ochinchina
    name: sipproxy
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}"
