language: go
sudo: true
go:
- 1.13.x

env:
  global:
    - GO111MODULE=on
    - GORELEASER_VERSION=0.123.3
    - UPXVER="3.94"

before_install:
  - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  - sudo dpkg -i goreleaser_amd64.deb
  - |
    if [[ ! -f "upx/${UPXVER}/upx" ]]
    then
      echo "Installing upx .."
      curl -OL "https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz"
      tar xvf "upx-${UPXVER}-amd64_linux.tar.xz"
      mkdir -p upx
      mv "upx-${UPXVER}-amd64_linux" "upx/${UPXVER}"
    fi
  - export PATH="${TRAVIS_BUILD_DIR}/upx/${UPXVER}/:${PATH}"
  - upx --version | grep -E '^upx'
  - chmod +x upx.sh
  - go install github.com/UnnoTed/fileb0x

script:
  - go test -v ./...
  - goreleaser --skip-validate --skip-sign --debug

branches:
  only:
    - master
